### PR TITLE
Added fstab and director creation

### PR DESCRIPTION
**Pull request by sgreenslade**
Hi,

I've made a minor change to the recipe to allow it to create the mount folder (if it does not exist) and also to add a record to fstab.

Cheers

Steve

### CODE REVIEW

**Comment by realityforge** [comment]
This change would result in an unmount and remount every time a chef converge ran. We converge the node many times an hour and this would cause us a few problems. The way to fix this so an unmount is not necessary is to set the following smfs options
- uid
- gid
- fmask
- dmask

If the directory is created with the same permissions/owners as it will be mounted with then the directory resource will not result in an error. I will look at what we do with our infrastructure on Monday to see if I can figure out a way to incorporate this patch without unmounting the drive.

**Comment by realityforge** [comment]
Thanks by the way!

**Comment by sgreenslade** [comment]
Hi Peter,

Ah I see there might be a better solution.  We only run chef by hand for
the occasional update,  I'd not thought about the regular chef updates.

I'd be interested to see how setting these other options might work.

Many thanks

Steve

PS we love the glassfish recipe too :-)

**Comment by realityforge** [comment]
Hi, so it looks like I wont have a chance to look at this before I head away on holidays. However, most of our mounts have an options hash something like

``` ruby
    'options' =>
      {
        'rw' => nil,
        'dir_mode' => '0700',
        'file_mode' => '0600',
        'noserverino' => nil,
        'uid' => node['glassfish']['user'],
        'gid' => node['glassfish']['group']
      }
```

And then we make sure that when we create the directory we make sure we set the same permissions such as 

``` ruby
directory '/mn/mydir' do
    owner node['glassfish']['user']
    group node['glassfish']['group']
    mode '0700'
    action :create
  end
```

And thus we don't have to unmount before creating the directory.

**Comment by realityforge** [comment]
I will try and look at this when I get back

**Comment by sgreenslade** [comment]
Hi Peter,

That's very interesting.
I'll give that a try at work today and let you know how I get on.

Many thanks

Steve

**Comment by sgreenslade** [comment]
Hi Peter,

I've tried that approach, but on my DEV server (Ubuntu Server 13.04) the
second time that Chef-Client runs I get a permissions error.

# 

# Error executing action `create` on resource 'directory[/mnt/my_files]'

...

Errno::EACCES: Permission denied - /mnt/my_files

If I unmount the folder and run Chef-Client again it works fine.

So there is something going on when chef checks the mounted directory.

I've come up with a (slightly) better work arround, by including a not_if
in the directory command.

# Create the directory if it does not exist.

directory new_resource.path do
owner new_resource.dir_owner
group new_resource.dir_group
mode new_resource.dir_mode
recursive false
action [:create]
not_if { ::File.exists?(new_resource.path)}
end

This happily skips folder directory creation if the directory already
exsist.... feels a bit of a hack, but it seems to work.

Happy holidays

Steve

**Comment by realityforge** [comment]
I have attempted to hand migrate your changes in and create directories based on the extra options created. Can you check and make sure it works for you?

```
node.override['smbfs']['mounts'][upload_dir] =
  {
        'cifs_path' => '//san01.example.org/myshare$/Some/Path',
        'username' => 'MyUser',
        'password' => 'MyPass',
        'options' =>
          {
            'rw' => nil,
            'dir_mode' => '0700',
            'file_mode' => '0600',
            'noserverino' => nil,
            'uid' => 'myuser',
            'gid' => 'mygroup'
          }
  }
```

**Comment by realityforge** [comment]
Assuming this works as we have been using it for years with no isses

**Pull request closed without merging**
